version: '2'
services:
    sese_translator-app:
        image: sese_translator
        external_links:
            - sese_translator-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/sese_translator
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sese_translator-postgresql:
        extends:
            file: postgresql.yml
            service: sese_translator-postgresql
